
import DB.CarroDAO;
import Model.ListCarros;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cliente
 */
public class LayoutLoja extends javax.swing.JFrame {

    /**
     * Creates new form LayoutLoja
     */
    public LayoutLoja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Gtr35 = new javax.swing.JLabel();
        jkoenigsegg = new javax.swing.JLabel();
        jGtr34 = new javax.swing.JLabel();
        jGtr36 = new javax.swing.JLabel();
        koeni = new javax.swing.JLabel();
        jTitle = new javax.swing.JLabel();
        jValor1 = new javax.swing.JButton();
        jValor2 = new javax.swing.JButton();
        jValor3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCars = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/images.jpg"))); // NOI18N
        jLabel1.setLabelFor(jGtr34);
        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Gtr35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gtr35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download.jpg"))); // NOI18N
        Gtr35.setLabelFor(Gtr35);
        Gtr35.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jkoenigsegg.setBackground(new java.awt.Color(255, 255, 51));
        jkoenigsegg.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jkoenigsegg.setForeground(new java.awt.Color(255, 255, 255));
        jkoenigsegg.setLabelFor(koeni);
        jkoenigsegg.setText("koenigsegg agera r");
        jkoenigsegg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jGtr34.setBackground(new java.awt.Color(255, 255, 51));
        jGtr34.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jGtr34.setForeground(new java.awt.Color(255, 255, 255));
        jGtr34.setLabelFor(jGtr34);
        jGtr34.setText("Skyline GTr r34");
        jGtr34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jGtr36.setBackground(new java.awt.Color(255, 255, 51));
        jGtr36.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jGtr36.setForeground(new java.awt.Color(255, 255, 255));
        jGtr36.setLabelFor(Gtr35);
        jGtr36.setText("Skyline GTr r35");
        jGtr36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        koeni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        koeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download (2).jpg"))); // NOI18N
        koeni.setLabelFor(koeni);
        koeni.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jTitle.setForeground(new java.awt.Color(255, 255, 255));
        jTitle.setText("Motors Sports");

        jValor1.setBackground(new java.awt.Color(204, 204, 204));
        jValor1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jValor1.setText("Valor");
        jValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor1ActionPerformed(evt);
            }
        });

        jValor2.setBackground(new java.awt.Color(204, 204, 204));
        jValor2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jValor2.setText("Valor");
        jValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor2ActionPerformed(evt);
            }
        });

        jValor3.setBackground(new java.awt.Color(204, 204, 204));
        jValor3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jValor3.setText("Valor");
        jValor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor3ActionPerformed(evt);
            }
        });

        jTblCars.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        jTblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "marca", "modelo", "ano", "preco", "vendedorId"
            }
        ));
        jScrollPane1.setViewportView(jTblCars);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jGtr34, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jGtr36, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jkoenigsegg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Gtr35)
                .addGap(63, 63, 63)
                .addComponent(koeni, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jValor1)
                .addGap(448, 448, 448)
                .addComponent(jValor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jValor3)
                .addGap(210, 210, 210))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(koeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Gtr35, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jkoenigsegg)
                        .addComponent(jGtr34))
                    .addComponent(jGtr36))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jValor1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jValor2)
                        .addComponent(jValor3)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValor1ActionPerformed

    private void jValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValor2ActionPerformed

    private void jValor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor3ActionPerformed
       
    }//GEN-LAST:event_jValor3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    void mostra(){
        //limpando a tabela
       jTblCars.setModel(new DefaultTableModel(null,new String[]{"id","marca", "modelo", "ano", "preco", "vendedorId"}));
       
        DefaultTableModel model = 
                (DefaultTableModel)jTblCars.getModel();
        Object rowData[] = new Object[9];// qtd colunas
        Iterable<ListCarros> lista = null;
        for(ListCarros l: lista)
        {
            rowData[0] = l.getId();
            rowData[1] = l.getMarca();
            rowData[2] = l.getModelo();
            rowData[3] = l.getAno();
            rowData[4] = l.getPreco();
            rowData[5] = l.getVendedorId();
            model.addRow(rowData);
        }// fim preenche modelo
    }// fim mostra
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutLoja().setVisible(true);
                
                CarroDAO carroDAO = new CarroDAO();
        List<ListCarros> carros = carroDAO.carregaCarrosDoBanco();

        // Faça o que desejar com a lista de carros recuperados do banco de dados
        for (ListCarros carro : carros) {
            System.out.println(carro);
            }
          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gtr35;
    private javax.swing.JLabel jGtr34;
    private javax.swing.JLabel jGtr36;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTblCars;
    private javax.swing.JLabel jTitle;
    private javax.swing.JButton jValor1;
    private javax.swing.JButton jValor2;
    private javax.swing.JButton jValor3;
    private javax.swing.JLabel jkoenigsegg;
    private javax.swing.JLabel koeni;
    // End of variables declaration//GEN-END:variables
}
